# Generated by Django 4.2.7 on 2024-06-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=128)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to="user.user",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        help_text="Team members list", to="user.user"
                    ),
                ),
            ],
        ),
    ]
